---
title: "Audiência das temporadas de Rick and Morty"
author: "Will"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(ggplot2)
source("../R/tema_rick_morty.R")
```


```{r echo=FALSE}
rick_and_morty <- readr::read_rds("../data/rick_and_morty.rds")
```

Os dados foram obtidos no site [Wikipedia](https://en.wikipedia.org/wiki/List_of_Rick_and_Morty_episodes).

## Gráfico da audiência por episódio

```{r echo=FALSE, dpi = 300}
rick_and_morty %>%
  mutate(num_temporada = as.factor(num_temporada)) %>%
  ggplot() +
  geom_col(aes(x = num_episodio,
               y = qtd_espectadores_EUA,
               fill = num_temporada)) +
  labs(x = "Numero do episodio",
       y = "Audiencia nos EUA",
       fill = "Temporada",
       title = "Audiencia de episodios \n de Rick and Morty") +
  tema_rick_morty() +
  scale_fill_rick_morty()
```

## Gráfico de audiência média por temporada

```{r echo=FALSE, api = 300}
rick_and_morty %>%
  mutate(num_temporada = as.factor(num_temporada)) %>%
  group_by(num_temporada) %>%
  summarise(audiencia_media = mean(qtd_espectadores_EUA, na.rm = TRUE)) %>%
  
  ggplot() +
  geom_col(aes(x = num_temporada,
               y = audiencia_media,
               fill = num_temporada),
           show.legend = FALSE) +
  labs(x = "Temporada",
       y = "Audiencia media nos EUA",
       title = "Audiencia de temporadas \n de Rick and Morty") +
  tema_rick_morty() +
  scale_fill_rick_morty()
```

